// ═══════════════════════════════════════════════════════════════════════════════
// AURA PUBLISHING — SKILL REGISTRY (30 State-of-the-Art Skills)
// Stored in RAG library for runtime retrieval by agents
// ═══════════════════════════════════════════════════════════════════════════════

export interface SkillDef {
  id: string;
  name: string;
  category: string;
  description: string;
  triggerKeywords: string[];
  executionSteps: string[];
  tools: string[];
  agentType: "planner" | "search" | "media" | "social" | "any";
  complexity: "simple" | "medium" | "complex";
  contextRequired: string[];
  outputFormat: string;
  examples: string[];
  siePhase: string; // Which SIE phase this skill maps to
}

export const SKILL_REGISTRY: SkillDef[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: Book Marketing & Launch Strategy (Skills 1-6)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_001",
    name: "Book Launch Campaign Architect",
    category: "book_marketing",
    description: "Designs comprehensive multi-phase book launch campaigns with pre-launch, launch day, and post-launch strategies including timeline, budget allocation, and platform selection.",
    triggerKeywords: ["launch", "campaign", "book release", "debut", "publication", "go live", "drop"],
    executionSteps: [
      "Analyze book metadata (genre, audience, themes, unique angles)",
      "Research comparable successful launches in the same genre",
      "Design 3-phase timeline: Pre-launch (4-8 weeks), Launch Week, Post-launch (4-12 weeks)",
      "Select optimal platform mix based on target demographics",
      "Create content calendar with 20+ touchpoints per phase",
      "Define KPIs and success metrics for each phase",
      "Generate campaign brief with budget recommendations",
    ],
    tools: ["think", "web_search", "create_campaign"],
    agentType: "planner",
    complexity: "complex",
    contextRequired: ["bookId", "genre", "targetAudience", "publishDate"],
    outputFormat: "Campaign plan with timeline, platform mix, content calendar, and KPIs",
    examples: ["Create a launch campaign for my sci-fi novel targeting young adults", "Plan a 6-week pre-launch for my cookbook"],
    siePhase: "P → A → INT → RUN → V",
  },
  {
    id: "skill_002",
    name: "Genre Market Analyzer",
    category: "book_marketing",
    description: "Deep analysis of genre-specific market conditions including competitor positioning, pricing strategies, trending themes, reader demographics, and market saturation.",
    triggerKeywords: ["market analysis", "genre research", "competitor", "market size", "trending", "reader demographics"],
    executionSteps: [
      "Search for top 20 books in target genre (last 12 months)",
      "Analyze competitor positioning and unique selling propositions",
      "Research pricing strategies across formats (ebook, paperback, hardcover, audiobook)",
      "Identify trending themes, tropes, and reader preferences",
      "Map reader demographics (age, gender, location, reading habits)",
      "Assess market saturation and opportunity gaps",
      "Generate actionable positioning recommendations",
    ],
    tools: ["web_search", "web_scrape", "think"],
    agentType: "search",
    complexity: "complex",
    contextRequired: ["genre", "bookTitle", "targetAudience"],
    outputFormat: "Market analysis report with competitor matrix, pricing data, trend analysis, and positioning recommendations",
    examples: ["Analyze the cozy mystery market for my new series", "What's the current state of YA fantasy?"],
    siePhase: "O → INSPECT → GAP → P",
  },
  {
    id: "skill_003",
    name: "Author Brand Builder",
    category: "book_marketing",
    description: "Develops author brand identity including voice guidelines, visual identity recommendations, content pillars, and platform-specific brand strategies.",
    triggerKeywords: ["brand", "author platform", "identity", "voice", "persona", "author profile"],
    executionSteps: [
      "Analyze author's existing online presence and content",
      "Define brand voice (tone, vocabulary, values, personality traits)",
      "Create 5 content pillars for consistent messaging",
      "Design visual identity guidelines (color palette, imagery style, typography)",
      "Map platform-specific brand adaptations",
      "Create brand voice cheat sheet with do's and don'ts",
      "Generate sample branded content for each platform",
    ],
    tools: ["think", "web_search", "generate_image"],
    agentType: "planner",
    complexity: "medium",
    contextRequired: ["authorName", "genre", "existingPresence"],
    outputFormat: "Brand guide with voice guidelines, visual identity, content pillars, and platform strategies",
    examples: ["Build my author brand as a thriller writer", "Create a brand identity for my cozy mystery persona"],
    siePhase: "P → A → INT → V",
  },
  {
    id: "skill_004",
    name: "Book Blurb & Copy Optimizer",
    category: "book_marketing",
    description: "Crafts compelling book descriptions, back cover copy, taglines, and marketing copy optimized for conversion across retailers and social platforms.",
    triggerKeywords: ["blurb", "description", "synopsis", "tagline", "back cover", "copy", "hook", "elevator pitch"],
    executionSteps: [
      "Analyze book's core conflict, stakes, and emotional hooks",
      "Research successful blurbs in the same genre for patterns",
      "Craft 3 versions: short (50 words), medium (150 words), long (300 words)",
      "Write 5 tagline options",
      "Optimize for retailer algorithms (keyword-rich, genre signals)",
      "Adapt copy for each platform (Amazon, Goodreads, Instagram, etc.)",
      "A/B test framework for measuring conversion",
    ],
    tools: ["think", "web_search"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookTitle", "genre", "plotSummary", "targetAudience"],
    outputFormat: "Complete copy package with multiple lengths, taglines, and platform adaptations",
    examples: ["Write a compelling blurb for my romance novel", "Create taglines for my sci-fi trilogy"],
    siePhase: "P → A → TEST → V",
  },
  {
    id: "skill_005",
    name: "Pricing Strategy Engine",
    category: "book_marketing",
    description: "Determines optimal pricing strategy using competitive analysis, price elasticity modeling, promotional timing, and revenue optimization.",
    triggerKeywords: ["price", "pricing", "revenue", "discount", "promotion", "sale", "launch price"],
    executionSteps: [
      "Research pricing of top 20 comparable titles",
      "Analyze price points by format (ebook, paperback, hardcover, audio)",
      "Model promotional strategies (intro pricing, countdown deals, free days)",
      "Design price testing framework",
      "Calculate break-even and optimal price points",
      "Plan promotional calendar with pricing tiers",
      "Generate revenue projection scenarios",
    ],
    tools: ["web_search", "think"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["genre", "bookLength", "formatTypes", "productionCost"],
    outputFormat: "Pricing strategy with competitive analysis, promotional calendar, and revenue projections",
    examples: ["What's the best price for my 300-page fantasy ebook?", "Plan a promotional pricing strategy for launch week"],
    siePhase: "O → INSPECT → P → A → V",
  },
  {
    id: "skill_006",
    name: "ARC & Review Generation System",
    category: "book_marketing",
    description: "Manages Advance Reader Copy distribution, review generation campaigns, and social proof building through strategic reviewer outreach.",
    triggerKeywords: ["ARC", "review", "advanced reader", "beta reader", "reviewer", "social proof", "early copy"],
    executionSteps: [
      "Identify target review platforms (Goodreads, NetGalley, BookSirens, Reedsy)",
      "Create ARC outreach template and targeting criteria",
      "Design review incentive strategy (giveaways, exclusive content)",
      "Build reviewer tracking and follow-up system",
      "Plan review amplification strategy (quote cards, testimonial posts)",
      "Create review milestone timeline",
      "Generate thank-you and engagement templates",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "launchDate", "reviewGoals"],
    outputFormat: "ARC campaign plan with outreach templates, platform strategy, and review tracking system",
    examples: ["Set up an ARC campaign for my thriller", "Get 50 reviews before launch day"],
    siePhase: "P → A → INT → RUN → V → CMP",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: Social Media Platform Mastery (Skills 7-14)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_007",
    name: "Instagram Visual Storyteller",
    category: "social_media",
    description: "Creates Instagram-optimized content including carousel posts, Reels scripts, Stories sequences, and aesthetic grid planning for book promotion.",
    triggerKeywords: ["instagram", "IG", "reel", "carousel", "grid", "visual", "aesthetic"],
    executionSteps: [
      "Design visual theme and grid layout strategy",
      "Create 5 carousel post concepts with slide-by-slide scripts",
      "Write 3 Reels scripts with hook, story, and CTA",
      "Plan Stories sequence (teaser → behind-scenes → launch → engagement)",
      "Generate hashtag strategy (3-tier: niche, mid, broad)",
      "Design engagement tactics (polls, quizzes, AMAs)",
      "Create content calendar with optimal posting times",
    ],
    tools: ["think", "write_post", "generate_image"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "visualStyle", "targetAudience"],
    outputFormat: "Instagram content package with carousel scripts, Reels scripts, Stories plan, and hashtag strategy",
    examples: ["Create Instagram content for my romance novel launch", "Plan a Reels series for my fantasy book"],
    siePhase: "P → A → INT → RUN → TEST → V",
  },
  {
    id: "skill_008",
    name: "TikTok Viral Content Engine",
    category: "social_media",
    description: "Generates TikTok-optimized short-form video concepts, scripts, trending audio suggestions, and hashtag strategies for maximum book discovery.",
    triggerKeywords: ["tiktok", "short video", "viral", "trending", "booktok", "hook", "trend"],
    executionSteps: [
      "Research current BookTok trends and viral formats",
      "Create 5 video concepts with opening hooks (first 3 seconds)",
      "Write scripts optimized for 15s, 30s, and 60s formats",
      "Suggest trending audio and transition styles",
      "Design duet/stitch opportunity concepts",
      "Plan posting frequency and optimal times",
      "Create engagement response templates for comments",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "targetAge", "bookHooks"],
    outputFormat: "TikTok content package with video concepts, scripts, audio suggestions, and posting strategy",
    examples: ["Create TikTok ideas for my horror novel", "What's trending on BookTok for fantasy?"],
    siePhase: "O → P → A → RUN → V → CMP",
  },
  {
    id: "skill_009",
    name: "Facebook Community Builder",
    category: "social_media",
    description: "Builds and nurtures Facebook communities for authors including group strategy, event planning, ad copy, and engagement-driven content.",
    triggerKeywords: ["facebook", "group", "community", "event", "fb", "discussion", "live"],
    executionSteps: [
      "Design Facebook Group strategy (public vs private, entry questions)",
      "Create 10 discussion prompts to spark engagement",
      "Plan Facebook Live event schedule (Q&A, readings, workshops)",
      "Write ad copy for Facebook/Instagram ads",
      "Design group growth strategy (cross-promotion, giveaways)",
      "Create member onboarding sequence",
      "Plan community events calendar",
    ],
    tools: ["think", "write_post", "create_campaign"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "authorName", "communityGoals"],
    outputFormat: "Facebook community strategy with group plan, content calendar, event schedule, and ad copy",
    examples: ["Build a Facebook community for my romance readers", "Plan a Facebook Live launch event"],
    siePhase: "P → A → INT → RUN → V",
  },
  {
    id: "skill_010",
    name: "X (Twitter) Engagement Maximizer",
    category: "social_media",
    description: "Crafts X-optimized threads, tweets, and engagement strategies leveraging real-time conversation, hashtags, and community interaction for book buzz.",
    triggerKeywords: ["twitter", "x.com", "tweet", "thread", "viral tweet", "engagement", "retweet"],
    executionSteps: [
      "Research trending hashtags and conversations in book community",
      "Write 10 standalone tweets with hooks and CTAs",
      "Create 3 Twitter threads (story threads, tip threads, quote threads)",
      "Design engagement strategy (reply tactics, quote tweets, Spaces)",
      "Plan Twitter chat or AMA session",
      "Create author voice guidelines for X",
      "Build engagement tracking and response templates",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "social",
    complexity: "simple",
    contextRequired: ["bookId", "genre", "authorVoice"],
    outputFormat: "X content package with tweets, threads, engagement strategy, and hashtag plan",
    examples: ["Write a Twitter thread about my writing process", "Create tweets for my book launch day"],
    siePhase: "P → A → RUN → V",
  },
  {
    id: "skill_011",
    name: "YouTube Content Strategist",
    category: "social_media",
    description: "Develops YouTube content strategy including video concepts, SEO-optimized titles/descriptions, thumbnail ideas, and series planning for author channels.",
    triggerKeywords: ["youtube", "video", "channel", "vlog", "book trailer", "reading", "SEO"],
    executionSteps: [
      "Research successful author YouTube channels for best practices",
      "Create 10 video concepts (book trailers, readings, writing tips, vlogs)",
      "Write SEO-optimized titles and descriptions",
      "Design thumbnail concept descriptions",
      "Plan series structure and upload schedule",
      "Create end-screen and CTA strategies",
      "Generate keyword research for video SEO",
    ],
    tools: ["web_search", "think", "generate_video", "write_post"],
    agentType: "media",
    complexity: "complex",
    contextRequired: ["bookId", "genre", "channelGoals", "videoStyle"],
    outputFormat: "YouTube strategy with video concepts, SEO data, thumbnail ideas, and upload schedule",
    examples: ["Plan my author YouTube channel content", "Create a book trailer concept"],
    siePhase: "O → P → A → INT → RUN → V",
  },
  {
    id: "skill_012",
    name: "Reddit Authentic Marketer",
    category: "social_media",
    description: "Navigates Reddit's community-driven landscape with authentic value-first marketing through AMAs, community engagement, and subreddit-specific strategies.",
    triggerKeywords: ["reddit", "subreddit", "AMA", "community", "discussion", "upvote"],
    executionSteps: [
      "Identify relevant subreddits (genre-specific, writing, reading, book clubs)",
      "Analyze each subreddit's rules and culture",
      "Design value-first post strategy (no self-promotion violation)",
      "Plan AMA (Ask Me Anything) session",
      "Create engagement templates for genuine participation",
      "Design subtle book mention strategy",
      "Build karma and trust before promotional posts",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "authorBackground"],
    outputFormat: "Reddit strategy with subreddit targeting, engagement plan, AMA outline, and community guidelines",
    examples: ["How should I promote my book on Reddit?", "Plan a Reddit AMA for my sci-fi novel"],
    siePhase: "O → INSPECT → P → A → V",
  },
  {
    id: "skill_013",
    name: "Cross-Platform Content Adapter",
    category: "social_media",
    description: "Adapts a single piece of content into platform-native formats for all 6 networks (Instagram, TikTok, Facebook, X, YouTube, Reddit) while maintaining brand consistency.",
    triggerKeywords: ["cross-platform", "repurpose", "adapt", "multi-platform", "all platforms", "every platform"],
    executionSteps: [
      "Analyze core content piece and extract key messages",
      "Adapt for Instagram (visual + short caption + hashtags)",
      "Adapt for TikTok (video script + trending format)",
      "Adapt for Facebook (longer form + community angle)",
      "Adapt for X (concise + thread potential)",
      "Adapt for YouTube (longer video concept)",
      "Adapt for Reddit (value-first + discussion angle)",
      "Generate unified posting schedule across all platforms",
    ],
    tools: ["think", "write_post"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "contentPiece", "brandVoice"],
    outputFormat: "6-platform content adaptation with posting schedule and platform-specific optimizations",
    examples: ["Turn this book excerpt into posts for all platforms", "Adapt my launch announcement for every network"],
    siePhase: "P → A → INT → RUN → V → CMP",
  },
  {
    id: "skill_014",
    name: "Social Media Ad Copy Generator",
    category: "social_media",
    description: "Creates high-converting paid social media ad copy, targeting recommendations, and campaign structures for book promotion across Meta, TikTok, and X ads.",
    triggerKeywords: ["ad", "advertising", "paid", "sponsored", "facebook ads", "meta ads", "tiktok ads", "campaign"],
    executionSteps: [
      "Define campaign objective (awareness, traffic, conversions)",
      "Create 3 ad angles (emotional, rational, social proof)",
      "Write primary text, headline, and description for each angle",
      "Design targeting recommendations (interests, demographics, behaviors)",
      "Create A/B test structure",
      "Write CTA variations",
      "Generate budget allocation recommendations",
    ],
    tools: ["think", "write_post", "create_campaign"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "budget", "objective"],
    outputFormat: "Ad campaign package with copy, targeting, A/B tests, and budget recommendations",
    examples: ["Create Facebook ads for my book launch", "Write TikTok ad copy for my thriller"],
    siePhase: "P → A → TEST → V → OPT",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: AI Content Generation (Skills 15-20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_015",
    name: "Prompt Engineering Master",
    category: "content_generation",
    description: "Crafts state-of-the-art prompts for image and video generation optimized for book cover art, promotional imagery, and visual storytelling.",
    triggerKeywords: ["prompt", "image generation", "AI art", "cover art", "visual", "illustration", "artwork"],
    executionSteps: [
      "Analyze book themes, mood, and visual requirements",
      "Research current AI art styles and techniques",
      "Craft base prompt with subject, style, lighting, composition",
      "Add negative prompts for quality control",
      "Create prompt variations for different use cases (cover, social, promo)",
      "Optimize for specific platforms (square for IG, vertical for stories)",
      "Generate style-consistent prompt templates",
    ],
    tools: ["think", "generate_image", "web_search"],
    agentType: "media",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "themes", "mood", "visualStyle"],
    outputFormat: "Prompt library with base prompts, variations, negative prompts, and platform-specific adaptations",
    examples: ["Create prompts for my dark fantasy cover art", "Generate promotional images for my cozy mystery"],
    siePhase: "P → A → TEST → V → OPT",
  },
  {
    id: "skill_016",
    name: "Book Trailer & Video Producer",
    category: "content_generation",
    description: "Conceptualizes and plans book trailers, author videos, and promotional video content with scene breakdowns, music mood, and editing directions.",
    triggerKeywords: ["book trailer", "video", "promo video", "teaser", "trailer", "cinematic"],
    executionSteps: [
      "Analyze book's key scenes, quotes, and emotional beats",
      "Create scene-by-scene storyboard description",
      "Write voiceover script or text overlay sequence",
      "Recommend music mood and pacing",
      "Design thumbnail concepts",
      "Plan video specs per platform (aspect ratio, length)",
      "Generate production checklist and timeline",
    ],
    tools: ["think", "generate_video", "generate_image"],
    agentType: "media",
    complexity: "complex",
    contextRequired: ["bookId", "genre", "keyScenes", "targetMood", "duration"],
    outputFormat: "Video production plan with storyboard, script, music recommendations, and platform specs",
    examples: ["Create a book trailer concept for my horror novel", "Plan a 30-second teaser for TikTok"],
    siePhase: "P → A → INT → RUN → V",
  },
  {
    id: "skill_017",
    name: "Quote Card & Graphic Designer",
    category: "content_generation",
    description: "Creates quote cards, text graphics, and shareable visual content featuring book quotes, reviews, and promotional messages.",
    triggerKeywords: ["quote card", "graphic", "text image", "shareable", "quote", "meme", "infographic"],
    executionSteps: [
      "Extract top 10 quotable lines from the book",
      "Design layout concepts (typography, background, accent elements)",
      "Create variations: author quotes, character quotes, review quotes",
      "Design platform-specific dimensions (square, story, landscape)",
      "Plan quote card series for campaign",
      "Generate themed backgrounds and visual elements",
      "Create templates for easy future use",
    ],
    tools: ["think", "generate_image"],
    agentType: "media",
    complexity: "simple",
    contextRequired: ["bookId", "quotes", "brandColors", "visualStyle"],
    outputFormat: "Quote card designs with layout specs, typography recommendations, and platform dimensions",
    examples: ["Create quote cards from my novel", "Design shareable graphics with my best reviews"],
    siePhase: "P → A → RUN → V",
  },
  {
    id: "skill_018",
    name: "Email Marketing Sequence Writer",
    category: "content_generation",
    description: "Writes high-converting email sequences for book launches including welcome series, launch announcements, last-chance emails, and nurture campaigns.",
    triggerKeywords: ["email", "newsletter", "sequence", "mailing list", "subscriber", "campaign", "drip"],
    executionSteps: [
      "Define email sequence goal and subscriber segments",
      "Write subject lines (5 options per email for A/B testing)",
      "Craft email body with hook, story, offer, CTA structure",
      "Design send schedule and automation triggers",
      "Create segment-specific variations",
      "Write re-engagement and win-back sequences",
      "Generate performance tracking recommendations",
    ],
    tools: ["think", "write_post"],
    agentType: "social",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "listSize", "campaignGoal"],
    outputFormat: "Email sequence with subject lines, body copy, send schedule, and automation rules",
    examples: ["Write a 5-email launch sequence", "Create a welcome series for new subscribers"],
    siePhase: "P → A → TEST → V → OPT",
  },
  {
    id: "skill_019",
    name: "Blog & SEO Content Writer",
    category: "content_generation",
    description: "Creates SEO-optimized blog posts, articles, and long-form content that drives organic traffic while promoting the book and establishing author authority.",
    triggerKeywords: ["blog", "SEO", "article", "content marketing", "organic traffic", "keywords", "long-form"],
    executionSteps: [
      "Research keywords and topics with search volume in the genre",
      "Create content calendar with 10 topic ideas",
      "Write SEO-optimized blog post with title, meta, headers",
      "Include natural book mentions and CTAs",
      "Design internal linking strategy",
      "Create social sharing snippets",
      "Generate content upgrade ideas (checklists, guides)",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "keywords", "blogTone"],
    outputFormat: "Blog content package with SEO data, articles, meta descriptions, and sharing snippets",
    examples: ["Write blog posts to promote my cookbook", "Create SEO content for my fantasy series"],
    siePhase: "O → P → A → RUN → V → CMP",
  },
  {
    id: "skill_020",
    name: "Podcast & Interview Prepper",
    category: "content_generation",
    description: "Prepares authors for podcast appearances, interviews, and media features with talking points, story bank, and audience engagement strategies.",
    triggerKeywords: ["podcast", "interview", "media", "talking points", "PR", "publicity", "guest"],
    executionSteps: [
      "Research target podcasts and their audience",
      "Create 20 talking points organized by theme",
      "Develop signature stories and anecdotes",
      "Write elevator pitch and book summary (30s, 60s, 2min)",
      "Prepare answers to common interview questions",
      "Design audience engagement hooks (giveaways, CTA)",
      "Create follow-up and promotion plan for after appearance",
    ],
    tools: ["web_search", "think"],
    agentType: "planner",
    complexity: "medium",
    contextRequired: ["bookId", "authorBackground", "targetShows"],
    outputFormat: "Interview prep package with talking points, stories, pitches, and follow-up plan",
    examples: ["Prep me for my podcast tour", "Create talking points for my book interviews"],
    siePhase: "O → P → A → V",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: Analytics & Optimization (Skills 21-25)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_021",
    name: "Performance Analytics Dashboard",
    category: "analytics",
    description: "Designs analytics frameworks and KPI dashboards to track book marketing performance across all channels with actionable insights and optimization recommendations.",
    triggerKeywords: ["analytics", "KPI", "metrics", "dashboard", "performance", "tracking", "ROI"],
    executionSteps: [
      "Define key metrics for each platform (reach, engagement, conversion)",
      "Create measurement framework with attribution model",
      "Design dashboard structure and visualizations",
      "Set up benchmark targets by genre and platform",
      "Create weekly/monthly reporting templates",
      "Build alert system for underperforming content",
      "Generate optimization recommendations framework",
    ],
    tools: ["think", "web_search"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["campaignId", "platforms", "goals"],
    outputFormat: "Analytics framework with KPI definitions, dashboard design, reporting templates, and benchmarks",
    examples: ["Set up analytics for my launch campaign", "What KPIs should I track for book marketing?"],
    siePhase: "O → INSPECT → P → V → CMP → OPT",
  },
  {
    id: "skill_022",
    name: "A/B Testing Framework Designer",
    category: "analytics",
    description: "Creates structured A/B testing plans for book marketing elements including covers, blurbs, ad copy, pricing, and email subject lines with statistical rigor.",
    triggerKeywords: ["A/B test", "split test", "experiment", "test", "optimize", "variant"],
    executionSteps: [
      "Identify testable elements (covers, titles, blurbs, pricing, CTAs)",
      "Formulate hypotheses for each test",
      "Design test structure (sample size, duration, success criteria)",
      "Create variant specifications",
      "Plan testing calendar and sequence",
      "Define statistical significance thresholds",
      "Generate results interpretation guide",
    ],
    tools: ["think", "web_search"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["testElements", "audienceSize", "testDuration"],
    outputFormat: "A/B testing plan with hypotheses, variants, sample sizes, and success criteria",
    examples: ["Design an A/B test for my book cover", "Test which blurb converts better"],
    siePhase: "P → A → TEST → V → CMP → OPT",
  },
  {
    id: "skill_023",
    name: "Trend Surveillance & Hijacker",
    category: "analytics",
    description: "Monitors real-time trends across social media, news, and culture to identify opportunities for timely, relevant book marketing content.",
    triggerKeywords: ["trend", "trending", "news", "timely", "viral", "moment marketing", "culture"],
    executionSteps: [
      "Search current trending topics in book community and broader culture",
      "Analyze trend relevance to book themes and genre",
      "Identify trend lifecycle stage (emerging, peak, declining)",
      "Create content concepts that connect book to trend",
      "Design rapid-response workflow for trend hijacking",
      "Plan content calendar with tentpole events",
      "Generate real-time monitoring checklist",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "search",
    complexity: "simple",
    contextRequired: ["bookId", "genre", "themes"],
    outputFormat: "Trend report with opportunity analysis, content concepts, and rapid-response workflow",
    examples: ["What's trending that I can use to promote my book?", "Find trends relevant to my sci-fi novel"],
    siePhase: "O → INSPECT → P → A → RUN → V",
  },
  {
    id: "skill_024",
    name: "Audience Intelligence Profiler",
    category: "analytics",
    description: "Builds detailed reader personas and audience profiles using demographic, psychographic, and behavioral data for precision targeting.",
    triggerKeywords: ["audience", "reader persona", "demographics", "target reader", "ideal reader", "profile"],
    executionSteps: [
      "Research reader demographics for the genre",
      "Analyze psychographics (values, interests, lifestyle)",
      "Map behavioral patterns (where they buy, how they discover books)",
      "Create 3-5 detailed reader personas",
      "Identify lookalike audiences and expansion opportunities",
      "Map persona to platform preferences",
      "Generate targeting recommendations for ads",
    ],
    tools: ["web_search", "think"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["genre", "bookThemes", "existingReaders"],
    outputFormat: "Audience intelligence report with personas, demographic data, and targeting recommendations",
    examples: ["Who is my ideal reader?", "Create reader personas for my thriller"],
    siePhase: "O → INSPECT → P → A → V",
  },
  {
    id: "skill_025",
    name: "Conversion Funnel Optimizer",
    category: "analytics",
    description: "Maps and optimizes the reader journey from awareness to purchase including touchpoint analysis, friction identification, and conversion rate optimization.",
    triggerKeywords: ["funnel", "conversion", "journey", "sales", "purchase", "buy", "reader journey"],
    executionSteps: [
      "Map complete reader journey (awareness → interest → consideration → purchase → advocacy)",
      "Identify all touchpoints across platforms",
      "Analyze conversion rates at each funnel stage",
      "Identify friction points and drop-off reasons",
      "Design optimization experiments for each stage",
      "Create retargeting strategy for abandoned journeys",
      "Generate funnel performance dashboard design",
    ],
    tools: ["think", "web_search"],
    agentType: "search",
    complexity: "complex",
    contextRequired: ["bookId", "platforms", "currentSalesData"],
    outputFormat: "Funnel analysis with journey map, touchpoint analysis, optimization plan, and retargeting strategy",
    examples: ["Optimize my book sales funnel", "Map the reader journey from social media to purchase"],
    siePhase: "O → INSPECT → GAP → P → A → TEST → V → OPT",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: AI Agent Operations (Skills 26-28)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_026",
    name: "Multi-Agent Crew Orchestrator",
    category: "agent_operations",
    description: "Coordinates multiple AI agents (Planner, Research, Media, Social) to execute complex publishing workflows with task delegation and quality review.",
    triggerKeywords: ["crew", "multi-agent", "orchestrate", "delegate", "workflow", "team", "collaborate"],
    executionSteps: [
      "Analyze complex goal and decompose into sub-tasks",
      "Assign each sub-task to optimal agent type",
      "Define task dependencies and execution order",
      "Set quality checkpoints and review gates",
      "Monitor agent execution and handle failures",
      "Aggregate outputs into unified deliverable",
      "Run final quality verification across all agent outputs",
    ],
    tools: ["think", "web_search", "generate_image", "write_post", "create_campaign"],
    agentType: "planner",
    complexity: "complex",
    contextRequired: ["goal", "bookId", "timeline"],
    outputFormat: "Orchestrated workflow result with all agent outputs integrated and quality-verified",
    examples: ["Run a complete launch campaign with all agents", "Coordinate research and content creation"],
    siePhase: "P → PRI → A → INT → RUN → TEST → V → FV",
  },
  {
    id: "skill_027",
    name: "Self-Reflection & Correction Engine",
    category: "agent_operations",
    description: "Activates deep self-reflection on agent decisions to prevent hallucination, verify goal alignment, and auto-correct misaligned actions before execution.",
    triggerKeywords: ["reflect", "verify", "check", "audit", "alignment", "self-correct", "quality check"],
    executionSteps: [
      "Capture agent's intended decision and reasoning",
      "Compare decision against user's stated goal",
      "Evaluate alignment across 4 dimensions: goal fit, efficiency, tool correctness, grounding",
      "Score decision confidence (0-100%)",
      "If score < 70%, generate correction suggestion",
      "Apply correction and re-evaluate",
      "Log reflection for continuous improvement",
    ],
    tools: ["think"],
    agentType: "any",
    complexity: "medium",
    contextRequired: ["userGoal", "agentDecision", "availableTools"],
    outputFormat: "Reflection report with alignment score, analysis, and correction if needed",
    examples: ["Check if this plan aligns with my goals", "Verify this decision before executing"],
    siePhase: "V → Δ → RCA → FIX → RETEST",
  },
  {
    id: "skill_028",
    name: "RAG Memory Context Injector",
    category: "agent_operations",
    description: "Retrieves and injects relevant memories from the scratch pad into agent prompts to maintain context continuity and prevent redundant work.",
    triggerKeywords: ["memory", "recall", "context", "remember", "previous", "rag", "retrieval"],
    executionSteps: [
      "Extract keywords from current task and user goal",
      "Search scratch pad for relevant historical memories",
      "Rank results by relevance and recency",
      "Format retrieved context for prompt injection",
      "Inject context into agent's working prompt",
      "Update access counts for retrieved memories",
      "Write new findings back to scratch pad after execution",
    ],
    tools: ["think"],
    agentType: "any",
    complexity: "medium",
    contextRequired: ["taskDescription", "agentType", "bookId"],
    outputFormat: "Contextualized prompt with relevant memories injected and new findings persisted",
    examples: ["Recall what we learned about my audience", "Use previous research for this task"],
    siePhase: "M → O → P → A → MEM",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CATEGORY: Publishing Operations (Skills 29-30)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skill_029",
    name: "Influencer & Bookstagrammer Outreach",
    category: "publishing_operations",
    description: "Identifies, evaluates, and manages relationships with book influencers, Bookstagrammers, and booktokers for review and promotion campaigns.",
    triggerKeywords: ["influencer", "bookstagram", "booktoker", "reviewer", "outreach", "collaboration", "partnership"],
    executionSteps: [
      "Search for relevant book influencers in the genre",
      "Evaluate influencers by engagement rate, audience fit, content quality",
      "Create tiered outreach list (mega, macro, micro, nano)",
      "Write personalized outreach templates for each tier",
      "Design collaboration proposals (reviews, giveaways, takeovers)",
      "Create tracking system for outreach and responses",
      "Plan long-term relationship nurturing strategy",
    ],
    tools: ["web_search", "think", "write_post"],
    agentType: "search",
    complexity: "medium",
    contextRequired: ["bookId", "genre", "budget", "targetReach"],
    outputFormat: "Influencer strategy with target list, outreach templates, collaboration ideas, and tracking system",
    examples: ["Find bookstagrammers for my romance novel", "Plan influencer outreach for launch"],
    siePhase: "O → P → A → INT → RUN → V",
  },
  {
    id: "skill_030",
    name: "Book Tour & Event Planner",
    category: "publishing_operations",
    description: "Plans virtual and physical book tour events including signings, readings, panels, and online events with logistics and promotion strategies.",
    triggerKeywords: ["book tour", "event", "signing", "reading", "launch party", "virtual event", "appearance"],
    executionSteps: [
      "Determine event format mix (virtual, in-person, hybrid)",
      "Research venues and platforms for each event type",
      "Create event timeline and logistics checklist",
      "Design event promotion strategy",
      "Plan audience engagement activities (Q&A, giveaways, photo ops)",
      "Create post-event follow-up and content repurposing plan",
      "Generate budget estimate and ROI projections",
    ],
    tools: ["web_search", "think", "write_post", "create_campaign"],
    agentType: "planner",
    complexity: "complex",
    contextRequired: ["bookId", "genre", "budget", "locations", "dates"],
    outputFormat: "Book tour plan with event schedule, logistics, promotion strategy, and budget",
    examples: ["Plan a virtual book tour", "Organize my launch week events"],
    siePhase: "P → A → INT → RUN → V → CMP",
  },
];

// ─── Skill Retrieval Utilities ───

export function findSkillsByKeyword(query: string): SkillDef[] {
  const q = query.toLowerCase();
  const scored = SKILL_REGISTRY.map((skill) => {
    let score = 0;
    // Match trigger keywords
    for (const kw of skill.triggerKeywords) {
      if (q.includes(kw.toLowerCase())) score += 3;
    }
    // Match name
    if (skill.name.toLowerCase().includes(q)) score += 2;
    // Match description
    if (skill.description.toLowerCase().includes(q)) score += 1;
    // Match category
    if (skill.category.toLowerCase().includes(q)) score += 1;
    return { skill, score };
  });
  return scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score).map((s) => s.skill);
}

export function findSkillsByAgentType(agentType: string): SkillDef[] {
  return SKILL_REGISTRY.filter((s) => s.agentType === agentType || s.agentType === "any");
}

export function findSkillsByCategory(category: string): SkillDef[] {
  return SKILL_REGISTRY.filter((s) => s.category === category);
}

export function getSkillById(id: string): SkillDef | undefined {
  return SKILL_REGISTRY.find((s) => s.id === id);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(SKILL_REGISTRY.map((s) => s.category)));
}
